AWSTemplateFormatVersion: "2010-09-09"
Description: "Reference: https://docs.aws.amazon.com/msk/latest/developerguide/getting-started.html"

Parameters:
  VpcIdDatabricksWorkspace:
    Type: AWS::EC2::VPC::Id

  VpcIdExternal:
    Type: AWS::EC2::VPC::Id
  
  CidrDatabricksWorkspace:
    Type: String
  
  CidrExternal:
    Type: String

  RouteTableIdCluster:
    Type: String
  
  RouteTableIdExternal:
    Type: String

  SecurityGroupIdDatabricksCluster:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  # ----------------------------------------
  # VPC Peering
  # ----------------------------------------
  VpcPeering:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref VpcIdDatabricksWorkspace
      PeerVpcId: !Ref VpcIdExternal
      Tags:
        - { Key: Name, Value: dbx-pcx-external }

  # ----------------------------------------
  # VPC Routing
  # ----------------------------------------
  RouteCluster:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableIdCluster
      DestinationCidrBlock: !Ref CidrExternal
      VpcPeeringConnectionId: !Ref VpcPeering
  
  RouteExternal:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableIdExternal
      DestinationCidrBlock: !Ref CidrDatabricksWorkspace
      VpcPeeringConnectionId: !Ref VpcPeering

  # ----------------------------------------
  # VPC Security Group
  # ----------------------------------------
  VpcSecurityGroupExternal:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: dbx-sg-external
      GroupDescription: databricks external resource security group
      VpcId: !Ref VpcIdExternal

  VpcSecurityGroupExternalIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: -1
      GroupId: !Ref VpcSecurityGroupExternal
      SourceSecurityGroupId: !Ref VpcSecurityGroupExternal

  VpcSecurityGroupExternalIngress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: -1
      GroupId: !Ref VpcSecurityGroupExternal
      SourceSecurityGroupId: !Ref SecurityGroupIdDatabricksCluster

  VpcSecurityGroupClusterIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: -1
      GroupId: !Ref SecurityGroupIdDatabricksCluster
      SourceSecurityGroupId: !Ref VpcSecurityGroupExternal

Outputs:
  VpcSecurityGroupIdExternal:
    Value: !Ref VpcSecurityGroupExternal
